---
title: "Exclusion I: speech presence"
jupyter: false
format:
  html:
    code-overflow: wrap
    code-width: 1200  # Adjust the width in pixels
execute:
  warning: false 
  enabled: false
toc: true
bibliography: ../references.bib
---

# Overview {#sec-excl-speech}

We used [Whisper](https://github.com/openai/whisper){target="_blank"} to check each trial for speech presence. Despite the fact that the algorithm hallucinates quite often, it still helps us to reduce the number of trials we need to check for potential speech presence.

In [ ]:
#| code-fold: true
#| code-summary: Code to prepare the environment

import os
import glob
import pandas as pd
import numpy as np

curfolder = os.getcwd()
cleaningfolder = os.path.join(curfolder, 'Cleaning')

# load the csv file
df = pd.read_csv(os.path.join(cleaningfolder, 'control_for_speech_check.csv'))
df.head()

,filename,check,start_time,end_time,has_speech,whisper_text
0,10_1_trial_11_Mic_nominal_srate48000_p1_vuur_c...,no speech,0.0,9.282875,True,Wat is dat?
1,10_1_trial_21_Mic_nominal_srate48000_p0_piepen...,no sound,0.0,9.297125,True,Ik heb het gevoel dat het een beetje te hard is.
2,10_1_trial_23_Mic_nominal_srate48000_p0_vangen...,no sound,0.0,10.808375,True,Wat is dat? Wat is dat?
3,10_1_trial_24_Mic_nominal_srate48000_p0_kauwen...,no sound,0.0,7.720625,True,Dank je wel.
4,10_1_trial_32_Mic_nominal_srate48000_p1_hond_g...,no sound,0.0,5534.000000,True,Dank u wel.

# Processing annotated file

This file contains all files flagged by Whisper for speech presence. Then, we manually inspected all sound files and annotated whether there is speech or not. Now we want to clean the annotated file so that only clear samples of speech use are left

In [3]:
# get rid of rows where check == no speech
df = df[df['check'] != 'no speech']

# get rid of rows where check == no sound
df = df[df['check'] != 'no sound']

# get rid of rows that contain string noisy or onisy
df = df[~df['check'].str.contains('noisy', case=False, na=False)]
df = df[~df['check'].str.contains('onisy', case=False, na=False)]

# get rid of rows that contain laugh or Laugh string
df = df[~df['check'].str.contains('laugh', case=False, na=False)]


df.head(15)

,filename,check,start_time,end_time,has_speech,whisper_text
159,19_1_trial_21_Mic_nominal_srate48000_p0_vrouw_...,speech cut,0.0,5.699937,True,Uw vrouw.
176,20_1_trial_16_Mic_nominal_srate48000_p1_kauwen...,speech? Ja,0.0,9.825875,True,Ik heb het gevoel dat ik een vrouw ben.
177,20_1_trial_17_Mic_nominal_srate48000_p1_slaan_...,speech?,0.0,5.242625,True,Kut.
190,20_2_trial_42_Mic_nominal_srate48000_p1_spring...,speech,0.0,10.173562,True,Wat is dat? ***
197,20_2_trial_66_Mic_nominal_srate48000_p1_blij_c...,speech,0.0,8.846187,True,Ik ga even kijken.
224,24_1_trial_40_Mic_nominal_srate48000_p0_scherp...,speech at the end?,0.0,5.606250,True,Wat is dat?
230,24_2_trial_27_Mic_nominal_srate48000_p1_bitter...,?,0.0,2.255375,True,Doe het goed.
256,26_2_trial_55_Mic_nominal_srate48000_p0_verbra...,speech,0.0,9.645938,True,Oud.
260,26_2_trial_6_Mic_nominal_srate48000_p0_kind_ge...,speech?,0.0,6.538687,True,Dank je wel voor het kijken.
264,27_1_trial_11_Mic_nominal_srate48000_p1_ik_com...,speech cut,0.0,21.121625,True,Dank u wel. *** ***
291,27_2_trial_95_Mic_nominal_srate48000_p1_stil_g...,speech?,0.0,13.039062,True,Mooi. ***
295,28_2_trial_33_Mic_nominal_srate48000_p0_bang_g...,speech,0.0,3.037313,True,"Oh, oh, oh."
349,30_2_trial_103_Mic_nominal_srate48000_p1_staar...,speech,0.0,13.763063,True,Dank u wel. Yes. Yes. Yes.
354,30_2_trial_30_Mic_nominal_srate48000_p1_kind_g...,"speech? mama, papa",0.0,4.209750,True,Mama. Papa.
355,30_2_trial_31_Mic_nominal_srate48000_p1_kind_g...,speech? mama papa,0.0,7.981438,True,Moema. Moema.

In [4]:
# save this
df.to_csv(os.path.join(cleaningfolder, 'control_for_speech_check_cleaned.csv'), index=False)